# Generated by Django 5.2.12 on 2026-03-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('institute_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('no_of_courses', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Institutes',
            },
        ),
    ]
